### ISSUE TITLE
 Inquiry about pretrained model (Braven) upload plans

### ISSUE THREAD

**Issue by JeongHun0716** [ahaliassos/raven#8]
The work you have done so far is truly impressive.

I am interested in using your pretrained model (BRAVEN, not fine-tuned model) for my experiments. However, I noticed that there isn't a pretrained model available in the repository at the moment. I wanted to inquire if you have any plans to upload a pretrained model in the near future.

**Comment by ahaliassos** [comment]
Thanks for the interest in our work and sorry for the late reply!

We have now added the pre-trained models to the repo. Hope it helps!
